# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yFRIAvMgWiFeu6rUdzbIZbpX4qumz3-i
"""

#Here we import the required libraries
import pandas
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
# Here we load the dataset to fetch the data
dataset1 = pd.read_csv('breastcancer.csv')
# Assign the variables to datasets
X=dataset1.iloc[:,2:31].values
Y=dataset1.iloc[:,1].values
labelencoder_Y = LabelEncoder()
Y= labelencoder_Y.fit_transform(Y)
#assigned here below
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X,Y,test_size=0.4, random_state=0)
# Here we create a model
my_first_nn1 = Sequential() 
# Here we see hidden layer
my_first_nn1.add(Dense(21, input_dim=31, activation='relu')) 
# Here we see another hidden layer
my_first_nn1.add(Dense(27)) 
# Here we get output layer
my_first_nn1.add(Dense(1, activation='sigmoid')) 
my_first_nn1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
my_first_nn_fitted1 = my_first_nn1.fit(X_train1, Y_train1, epochs=100,initial_epoch=0)
# Below output is made print statement
print(my_first_nn1.summary())
print(my_first_nn1.evaluate(X_test1, Y_test1))