# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X9WXmvH6gRgPyFjUt58x6DYVbzDjMLj9
"""

import pandas
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
sc = StandardScaler()
dataset1 = pd.read_csv('breastcancer.csv')
X=dataset1.iloc[:,2:31].values
Y=dataset1.iloc[:,1].values
labelencoder_Y = LabelEncoder()
Y= labelencoder_Y.fit_transform(Y)
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X,Y,test_size=0.4, random_state=0)
my_first_nn1 = Sequential() # create model
my_first_nn1.add(Dense(20, input_dim=29, activation='relu')) # hidden layer
my_first_nn1.add(Dense(25)) # hidden layer
my_first_nn1.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

my_first_nn_fitted1 = my_first_nn1.fit(X_train1, Y_train1, epochs=100,initial_epoch=0)
print(my_first_nn1.summary())
print(my_first_nn1.evaluate(X_test1, Y_test1))